<a href="https://colab.research.google.com/github/Matheus-Pombeiro/transformacao_manipulacao_dados/blob/main/transformacao_manipulacao_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Transformação e manipulação de dados**

## Preaparando o ambiente

In [ ]:
# Importando Pandas
import pandas as pd

# Importando NumPy
import numpy as np

In [ ]:
# Lendo o dataset
dados = pd.read_json('/content/dados_hospedagem.json')
dados.head()

                                         info_moveis
0  {'avaliacao_geral': '10.0', 'experiencia_local...
1  {'avaliacao_geral': '10.0', 'experiencia_local...
2  {'avaliacao_geral': '10.0', 'experiencia_local...
3  {'avaliacao_geral': '10.0', 'experiencia_local...
4  {'avaliacao_geral': '10.0', 'experiencia_local...

In [ ]:
# Preparando o dataset
dados = pd.json_normalize(dados['info_moveis'])
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

## Dados numéricos

In [ ]:
# Obtendo uma lista com os nomes das colunas
colunas = list(dados.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

In [ ]:
# Desagrupando dados com explode
dados = dados.explode(colunas[3:])
dados.head(3)

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00

In [ ]:
# Resetando o index dos dados
dados.reset_index(inplace=True, drop=True)
dados.head(3)

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00

In [ ]:
# Obtendo os tipos de dados
dados.info()

# object == varios tipos de dados em uma mesma coluna, tipo não identificado ou tipo string

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [ ]:
# Alterando o tipo de dados
dados['max_hospedes'] = dados['max_hospedes'].astype(np.int64)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

In [ ]:
col_numericas = ['quantidade_banheiros', 'quantidade_quartos', 'quantidade_camas']

In [ ]:
# Alterando o tipo de dados
dados[col_numericas] = dados[col_numericas].astype(np.int64)

In [ ]:
# Alterando o tipo de dados
dados['avaliacao_geral'] = dados['avaliacao_geral'].astype(np.float64)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [ ]:
# Removendo os caracteres especiais dos dados de preço
dados['preco'] = dados['preco'].apply(lambda x: x.replace('$', '').replace(',', '').strip())

In [ ]:
dados['preco'] = dados['preco'].astype(np.float64)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [ ]:
# Removendo caracteres especiais de mais de uma coluna
col_taxas = ['taxa_deposito', 'taxa_limpeza']
dados[col_taxas] = dados[col_taxas].map(lambda x: x.replace('$', '').replace(',', '').strip())

# apply == usado para uma series (linhas e colunas)
# map == usado para um dataframe (mais de uma series)

In [ ]:
# Alterando o tipo dos dados
dados[col_taxas] = dados[col_taxas].astype(np.float64)
dados[col_taxas].head(3)

   taxa_deposito  taxa_limpeza
0            0.0           0.0
1            0.0           0.0
2            0.0           0.0

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

## Dados Textuais

In [ ]:
dados['descricao_local'] = dados['descricao_local'].str.lower()
dados.head(2)

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,this clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,our century old upper queen anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0

In [ ]:
dados['descricao_local'][3169]

"built, run and supported by seattle tech and start up veterans, grokhome's focus is to create a supportive environment for smart people working on interesting projects, start ups and more. this listing is an upper bunk, in a 2-person shared room. *note: this fall, there will be major renovations happening on one kitchen and bathroom at a time. there will always be two other working kitchens and two working bathrooms in the house. we'll work to minimize the impact these renovations have on your stay. **this listing is only available to those working in the tech/science space. live in a hacker house, and immerse yourself in the seattle tech scene. you can expect to be surrounded by smart people solving big problems or working on something fun. we have frequent demo nights, and love when our guests share something they are passionate about. if you're new to the city, our deep ties to the seattle tech scene can help you get involved. expand your network, develop your ideas, and learn somet"

In [ ]:
dados['descricao_local'] = dados['descricao_local'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)
dados['descricao_local'].head(2)

# Regex:
# ^ == nega os valores a seguintes

0    this clean and comfortable one bedroom sits ri...
1    our century old upper queen anne house is loca...
Name: descricao_local, dtype: object

In [ ]:
# Substituindo hífens por espaços em branco, a não ser em caso de palavras compostas
dados['descricao_local'] = dados['descricao_local'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)

''' O regex (?<!\w)-(?!\w) procura por hífens (-) que não estejam ligados à palvras, substituindo-os por ' '
Exemplo == "hello-world-this-is-a-test-hyphenated-word" == "hello world this is a test hyphenated-word"'''

In [ ]:
# Separando as palavras
dados['descricao_local'] = dados['descricao_local'].str.split()
dados['descricao_local'].head(3)

0    [this, clean, and, comfortable, one, bedroom, ...
1    [our, century, old, upper, queen, anne, house,...
2    [cozy, room, in, two-bedroom, apartment, along...
Name: descricao_local, dtype: object

In [ ]:
# Removendo as {} e as '' de 'Comodidades'
dados['comodidades'] = dados['comodidades'].str.replace('\{|}|\"', '', regex=True)
dados['comodidades'].head(3)

0    Internet,Wireless Internet,Kitchen,Free Parkin...
1    TV,Internet,Wireless Internet,Kitchen,Free Par...
2    TV,Internet,Wireless Internet,Kitchen,Free Par...
Name: comodidades, dtype: object

In [ ]:
# Separando as palavras por vírgula
dados['comodidades'] = dados['comodidades'].str.split(',')
dados['comodidades'].head(3)

0    [Internet, Wireless Internet, Kitchen, Free Pa...
1    [TV, Internet, Wireless Internet, Kitchen, Fre...
2    [TV, Internet, Wireless Internet, Kitchen, Fre...
Name: comodidades, dtype: object

In [ ]:
# Verificando os dados de 'descricao_vizinhanca'
dados['descricao_vizinhanca'].head(3)

0    Lower Queen Anne is near the Seattle Center (s...
1    Upper Queen Anne is a really pleasant, unique ...
2    The convenience of being in Seattle but on the...
Name: descricao_vizinhanca, dtype: object

In [ ]:
# Convertendo as letras para tamanho minúsculo
dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.lower()
dados['descricao_vizinhanca'].head(3)

0    lower queen anne is near the seattle center (s...
1    upper queen anne is a really pleasant, unique ...
2    the convenience of being in seattle but on the...
Name: descricao_vizinhanca, dtype: object

In [ ]:
# Usando regex para manter apenas caracteres alfanuméricos, '-' e '''
dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)
dados['descricao_vizinhanca'].head(3)

0    lower queen anne is near the seattle center  s...
1    upper queen anne is a really pleasant  unique ...
2    the convenience of being in seattle but on the...
Name: descricao_vizinhanca, dtype: object

In [ ]:
# Substituindo hífens por espaços em branco, a não ser em caso de palavras compostas
dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)
dados['descricao_vizinhanca'].head(3)

0    lower queen anne is near the seattle center  s...
1    upper queen anne is a really pleasant  unique ...
2    the convenience of being in seattle but on the...
Name: descricao_vizinhanca, dtype: object

In [ ]:
# Separando as palavras
dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.split()
dados['descricao_vizinhanca'].head(3)

0    [lower, queen, anne, is, near, the, seattle, c...
1    [upper, queen, anne, is, a, really, pleasant, ...
2    [the, convenience, of, being, in, seattle, but...
Name: descricao_vizinhanca, dtype: object

## Dados de Tempo

In [ ]:
# Lendo a base de dados
dt_data = pd.read_json('/content/moveis_disponiveis.json')
dt_data.head(3)

    id        data  vaga_disponivel preco
0  857  2016-01-04            False  None
1  857  2016-01-05            False  None
2  857  2016-01-06            False  None

In [ ]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  object
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [ ]:
# Convertendo os valores da coluna 'data' o tipo datetime
dt_data['data'] = pd.to_datetime(dt_data['data'])

In [ ]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

In [ ]:
dt_data.head(3)

    id       data  vaga_disponivel preco
0  857 2016-01-04            False  None
1  857 2016-01-05            False  None
2  857 2016-01-06            False  None

In [ ]:
dt_data['data'].dt.strftime('%Y-%m').head(3)

0    2016-01
1    2016-01
2    2016-01
Name: data, dtype: object

In [ ]:
# Agrupando os dados por mês e número de vaga disponível
subset = dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
subset

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64

In [ ]:
# Preenchendo os valores vazios com a string '0.0'
dt_data['preco'] = dt_data['preco'].fillna('0.0')
dt_data['preco'].head(3)

0    0.0
1    0.0
2    0.0
Name: preco, dtype: object

In [ ]:
# Removendo '$' e ','
dt_data['preco'] = dt_data['preco'].apply(lambda x: x.replace('$', '').replace(',', ''))
dt_data['preco'].tail(3)

364997    140.00
364998    140.00
364999       0.0
Name: preco, dtype: object

In [ ]:
# Convertendo o tipo dos valores
dt_data['preco'] = dt_data['preco'].astype(np.float64)
dt_data['preco'].tail(3)

364997    140.0
364998    140.0
364999      0.0
Name: preco, dtype: float64

In [ ]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            365000 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1)
memory usage: 11.5 MB